// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.24.3
// source: protos/service/kv_service.proto

package service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	TSKVService_Ping_FullMethodName        = "/kv_service.TSKVService/Ping"
	TSKVService_WritePoints_FullMethodName = "/kv_service.TSKVService/WritePoints"
)

// TSKVServiceClient is the client API for TSKVService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TSKVServiceClient interface {
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	WritePoints(ctx context.Context, opts ...grpc.CallOption) (TSKVService_WritePointsClient, error)
}

type tSKVServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTSKVServiceClient(cc grpc.ClientConnInterface) TSKVServiceClient {
	return &tSKVServiceClient{cc}
}

func (c *tSKVServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, TSKVService_Ping_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tSKVServiceClient) WritePoints(ctx context.Context, opts ...grpc.CallOption) (TSKVService_WritePointsClient, error) {
	stream, err := c.cc.NewStream(ctx, &TSKVService_ServiceDesc.Streams[0], TSKVService_WritePoints_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &tSKVServiceWritePointsClient{stream}
	return x, nil
}

type TSKVService_WritePointsClient interface {
	Send(*WritePointsRequest) error
	Recv() (*WritePointsResponse, error)
	grpc.ClientStream
}

type tSKVServiceWritePointsClient struct {
	grpc.ClientStream
}

func (x *tSKVServiceWritePointsClient) Send(m *WritePointsRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *tSKVServiceWritePointsClient) Recv() (*WritePointsResponse, error) {
	m := new(WritePointsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TSKVServiceServer is the server API for TSKVService service.
// All implementations must embed UnimplementedTSKVServiceServer
// for forward compatibility
type TSKVServiceServer interface {
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	WritePoints(TSKVService_WritePointsServer) error
	mustEmbedUnimplementedTSKVServiceServer()
}

// UnimplementedTSKVServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTSKVServiceServer struct {
}

func (UnimplementedTSKVServiceServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedTSKVServiceServer) WritePoints(TSKVService_WritePointsServer) error {
	return status.Errorf(codes.Unimplemented, "method WritePoints not implemented")
}
func (UnimplementedTSKVServiceServer) mustEmbedUnimplementedTSKVServiceServer() {}

// UnsafeTSKVServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TSKVServiceServer will
// result in compilation errors.
type UnsafeTSKVServiceServer interface {
	mustEmbedUnimplementedTSKVServiceServer()
}

func RegisterTSKVServiceServer(s grpc.ServiceRegistrar, srv TSKVServiceServer) {
	s.RegisterService(&TSKVService_ServiceDesc, srv)
}

func _TSKVService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TSKVServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TSKVService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TSKVServiceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TSKVService_WritePoints_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TSKVServiceServer).WritePoints(&tSKVServiceWritePointsServer{stream})
}

type TSKVService_WritePointsServer interface {
	Send(*WritePointsResponse) error
	Recv() (*WritePointsRequest, error)
	grpc.ServerStream
}

type tSKVServiceWritePointsServer struct {
	grpc.ServerStream
}

func (x *tSKVServiceWritePointsServer) Send(m *WritePointsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *tSKVServiceWritePointsServer) Recv() (*WritePointsRequest, error) {
	m := new(WritePointsRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TSKVService_ServiceDesc is the grpc.ServiceDesc for TSKVService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TSKVService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kv_service.TSKVService",
	HandlerType: (*TSKVServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _TSKVService_Ping_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WritePoints",
			Handler:       _TSKVService_WritePoints_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "protos/service/kv_service.proto",
}
