// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: internal/service/kv_service.proto

package service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TSKVServiceClient is the client API for TSKVService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TSKVServiceClient interface {
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	WritePoints(ctx context.Context, opts ...grpc.CallOption) (TSKVService_WritePointsClient, error)
	WriteVnodePoints(ctx context.Context, in *WriteVnodeRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	QueryRecordBatch(ctx context.Context, in *QueryRecordBatchRequest, opts ...grpc.CallOption) (TSKVService_QueryRecordBatchClient, error)
	ExecAdminCommand(ctx context.Context, in *AdminCommandRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	DownloadFile(ctx context.Context, in *DownloadFileRequest, opts ...grpc.CallOption) (TSKVService_DownloadFileClient, error)
	GetVnodeFilesMeta(ctx context.Context, in *GetVnodeFilesMetaRequest, opts ...grpc.CallOption) (*GetVnodeFilesMetaResponse, error)
	FetchVnodeSummary(ctx context.Context, in *FetchVnodeSummaryRequest, opts ...grpc.CallOption) (*BatchBytesResponse, error)
	TagScan(ctx context.Context, in *QueryRecordBatchRequest, opts ...grpc.CallOption) (TSKVService_TagScanClient, error)
}

type tSKVServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTSKVServiceClient(cc grpc.ClientConnInterface) TSKVServiceClient {
	return &tSKVServiceClient{cc}
}

func (c *tSKVServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, "/kv_service.TSKVService/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tSKVServiceClient) WritePoints(ctx context.Context, opts ...grpc.CallOption) (TSKVService_WritePointsClient, error) {
	stream, err := c.cc.NewStream(ctx, &TSKVService_ServiceDesc.Streams[0], "/kv_service.TSKVService/WritePoints", opts...)
	if err != nil {
		return nil, err
	}
	x := &tSKVServiceWritePointsClient{stream}
	return x, nil
}

type TSKVService_WritePointsClient interface {
	Send(*WritePointsRequest) error
	Recv() (*WritePointsResponse, error)
	grpc.ClientStream
}

type tSKVServiceWritePointsClient struct {
	grpc.ClientStream
}

func (x *tSKVServiceWritePointsClient) Send(m *WritePointsRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *tSKVServiceWritePointsClient) Recv() (*WritePointsResponse, error) {
	m := new(WritePointsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *tSKVServiceClient) WriteVnodePoints(ctx context.Context, in *WriteVnodeRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, "/kv_service.TSKVService/WriteVnodePoints", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tSKVServiceClient) QueryRecordBatch(ctx context.Context, in *QueryRecordBatchRequest, opts ...grpc.CallOption) (TSKVService_QueryRecordBatchClient, error) {
	stream, err := c.cc.NewStream(ctx, &TSKVService_ServiceDesc.Streams[1], "/kv_service.TSKVService/QueryRecordBatch", opts...)
	if err != nil {
		return nil, err
	}
	x := &tSKVServiceQueryRecordBatchClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type TSKVService_QueryRecordBatchClient interface {
	Recv() (*BatchBytesResponse, error)
	grpc.ClientStream
}

type tSKVServiceQueryRecordBatchClient struct {
	grpc.ClientStream
}

func (x *tSKVServiceQueryRecordBatchClient) Recv() (*BatchBytesResponse, error) {
	m := new(BatchBytesResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *tSKVServiceClient) ExecAdminCommand(ctx context.Context, in *AdminCommandRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, "/kv_service.TSKVService/ExecAdminCommand", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tSKVServiceClient) DownloadFile(ctx context.Context, in *DownloadFileRequest, opts ...grpc.CallOption) (TSKVService_DownloadFileClient, error) {
	stream, err := c.cc.NewStream(ctx, &TSKVService_ServiceDesc.Streams[2], "/kv_service.TSKVService/DownloadFile", opts...)
	if err != nil {
		return nil, err
	}
	x := &tSKVServiceDownloadFileClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type TSKVService_DownloadFileClient interface {
	Recv() (*BatchBytesResponse, error)
	grpc.ClientStream
}

type tSKVServiceDownloadFileClient struct {
	grpc.ClientStream
}

func (x *tSKVServiceDownloadFileClient) Recv() (*BatchBytesResponse, error) {
	m := new(BatchBytesResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *tSKVServiceClient) GetVnodeFilesMeta(ctx context.Context, in *GetVnodeFilesMetaRequest, opts ...grpc.CallOption) (*GetVnodeFilesMetaResponse, error) {
	out := new(GetVnodeFilesMetaResponse)
	err := c.cc.Invoke(ctx, "/kv_service.TSKVService/GetVnodeFilesMeta", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tSKVServiceClient) FetchVnodeSummary(ctx context.Context, in *FetchVnodeSummaryRequest, opts ...grpc.CallOption) (*BatchBytesResponse, error) {
	out := new(BatchBytesResponse)
	err := c.cc.Invoke(ctx, "/kv_service.TSKVService/FetchVnodeSummary", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tSKVServiceClient) TagScan(ctx context.Context, in *QueryRecordBatchRequest, opts ...grpc.CallOption) (TSKVService_TagScanClient, error) {
	stream, err := c.cc.NewStream(ctx, &TSKVService_ServiceDesc.Streams[3], "/kv_service.TSKVService/TagScan", opts...)
	if err != nil {
		return nil, err
	}
	x := &tSKVServiceTagScanClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type TSKVService_TagScanClient interface {
	Recv() (*BatchBytesResponse, error)
	grpc.ClientStream
}

type tSKVServiceTagScanClient struct {
	grpc.ClientStream
}

func (x *tSKVServiceTagScanClient) Recv() (*BatchBytesResponse, error) {
	m := new(BatchBytesResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TSKVServiceServer is the server API for TSKVService service.
// All implementations must embed UnimplementedTSKVServiceServer
// for forward compatibility
type TSKVServiceServer interface {
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	WritePoints(TSKVService_WritePointsServer) error
	WriteVnodePoints(context.Context, *WriteVnodeRequest) (*StatusResponse, error)
	QueryRecordBatch(*QueryRecordBatchRequest, TSKVService_QueryRecordBatchServer) error
	ExecAdminCommand(context.Context, *AdminCommandRequest) (*StatusResponse, error)
	DownloadFile(*DownloadFileRequest, TSKVService_DownloadFileServer) error
	GetVnodeFilesMeta(context.Context, *GetVnodeFilesMetaRequest) (*GetVnodeFilesMetaResponse, error)
	FetchVnodeSummary(context.Context, *FetchVnodeSummaryRequest) (*BatchBytesResponse, error)
	TagScan(*QueryRecordBatchRequest, TSKVService_TagScanServer) error
	mustEmbedUnimplementedTSKVServiceServer()
}

// UnimplementedTSKVServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTSKVServiceServer struct {
}

func (UnimplementedTSKVServiceServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedTSKVServiceServer) WritePoints(TSKVService_WritePointsServer) error {
	return status.Errorf(codes.Unimplemented, "method WritePoints not implemented")
}
func (UnimplementedTSKVServiceServer) WriteVnodePoints(context.Context, *WriteVnodeRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WriteVnodePoints not implemented")
}
func (UnimplementedTSKVServiceServer) QueryRecordBatch(*QueryRecordBatchRequest, TSKVService_QueryRecordBatchServer) error {
	return status.Errorf(codes.Unimplemented, "method QueryRecordBatch not implemented")
}
func (UnimplementedTSKVServiceServer) ExecAdminCommand(context.Context, *AdminCommandRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecAdminCommand not implemented")
}
func (UnimplementedTSKVServiceServer) DownloadFile(*DownloadFileRequest, TSKVService_DownloadFileServer) error {
	return status.Errorf(codes.Unimplemented, "method DownloadFile not implemented")
}
func (UnimplementedTSKVServiceServer) GetVnodeFilesMeta(context.Context, *GetVnodeFilesMetaRequest) (*GetVnodeFilesMetaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVnodeFilesMeta not implemented")
}
func (UnimplementedTSKVServiceServer) FetchVnodeSummary(context.Context, *FetchVnodeSummaryRequest) (*BatchBytesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchVnodeSummary not implemented")
}
func (UnimplementedTSKVServiceServer) TagScan(*QueryRecordBatchRequest, TSKVService_TagScanServer) error {
	return status.Errorf(codes.Unimplemented, "method TagScan not implemented")
}
func (UnimplementedTSKVServiceServer) mustEmbedUnimplementedTSKVServiceServer() {}

// UnsafeTSKVServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TSKVServiceServer will
// result in compilation errors.
type UnsafeTSKVServiceServer interface {
	mustEmbedUnimplementedTSKVServiceServer()
}

func RegisterTSKVServiceServer(s grpc.ServiceRegistrar, srv TSKVServiceServer) {
	s.RegisterService(&TSKVService_ServiceDesc, srv)
}

func _TSKVService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TSKVServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kv_service.TSKVService/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TSKVServiceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TSKVService_WritePoints_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TSKVServiceServer).WritePoints(&tSKVServiceWritePointsServer{stream})
}

type TSKVService_WritePointsServer interface {
	Send(*WritePointsResponse) error
	Recv() (*WritePointsRequest, error)
	grpc.ServerStream
}

type tSKVServiceWritePointsServer struct {
	grpc.ServerStream
}

func (x *tSKVServiceWritePointsServer) Send(m *WritePointsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *tSKVServiceWritePointsServer) Recv() (*WritePointsRequest, error) {
	m := new(WritePointsRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _TSKVService_WriteVnodePoints_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteVnodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TSKVServiceServer).WriteVnodePoints(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kv_service.TSKVService/WriteVnodePoints",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TSKVServiceServer).WriteVnodePoints(ctx, req.(*WriteVnodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TSKVService_QueryRecordBatch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(QueryRecordBatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TSKVServiceServer).QueryRecordBatch(m, &tSKVServiceQueryRecordBatchServer{stream})
}

type TSKVService_QueryRecordBatchServer interface {
	Send(*BatchBytesResponse) error
	grpc.ServerStream
}

type tSKVServiceQueryRecordBatchServer struct {
	grpc.ServerStream
}

func (x *tSKVServiceQueryRecordBatchServer) Send(m *BatchBytesResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _TSKVService_ExecAdminCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TSKVServiceServer).ExecAdminCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kv_service.TSKVService/ExecAdminCommand",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TSKVServiceServer).ExecAdminCommand(ctx, req.(*AdminCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TSKVService_DownloadFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DownloadFileRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TSKVServiceServer).DownloadFile(m, &tSKVServiceDownloadFileServer{stream})
}

type TSKVService_DownloadFileServer interface {
	Send(*BatchBytesResponse) error
	grpc.ServerStream
}

type tSKVServiceDownloadFileServer struct {
	grpc.ServerStream
}

func (x *tSKVServiceDownloadFileServer) Send(m *BatchBytesResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _TSKVService_GetVnodeFilesMeta_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVnodeFilesMetaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TSKVServiceServer).GetVnodeFilesMeta(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kv_service.TSKVService/GetVnodeFilesMeta",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TSKVServiceServer).GetVnodeFilesMeta(ctx, req.(*GetVnodeFilesMetaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TSKVService_FetchVnodeSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchVnodeSummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TSKVServiceServer).FetchVnodeSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kv_service.TSKVService/FetchVnodeSummary",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TSKVServiceServer).FetchVnodeSummary(ctx, req.(*FetchVnodeSummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TSKVService_TagScan_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(QueryRecordBatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TSKVServiceServer).TagScan(m, &tSKVServiceTagScanServer{stream})
}

type TSKVService_TagScanServer interface {
	Send(*BatchBytesResponse) error
	grpc.ServerStream
}

type tSKVServiceTagScanServer struct {
	grpc.ServerStream
}

func (x *tSKVServiceTagScanServer) Send(m *BatchBytesResponse) error {
	return x.ServerStream.SendMsg(m)
}

// TSKVService_ServiceDesc is the grpc.ServiceDesc for TSKVService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TSKVService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kv_service.TSKVService",
	HandlerType: (*TSKVServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _TSKVService_Ping_Handler,
		},
		{
			MethodName: "WriteVnodePoints",
			Handler:    _TSKVService_WriteVnodePoints_Handler,
		},
		{
			MethodName: "ExecAdminCommand",
			Handler:    _TSKVService_ExecAdminCommand_Handler,
		},
		{
			MethodName: "GetVnodeFilesMeta",
			Handler:    _TSKVService_GetVnodeFilesMeta_Handler,
		},
		{
			MethodName: "FetchVnodeSummary",
			Handler:    _TSKVService_FetchVnodeSummary_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WritePoints",
			Handler:       _TSKVService_WritePoints_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "QueryRecordBatch",
			Handler:       _TSKVService_QueryRecordBatch_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "DownloadFile",
			Handler:       _TSKVService_DownloadFile_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "TagScan",
			Handler:       _TSKVService_TagScan_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "internal/service/kv_service.proto",
}
