// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.12
// source: internal/service/kv_service.proto

package service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// --------------------------------------------------------------------
type PingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version uint64 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Body    []byte `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_service_kv_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_service_kv_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_internal_service_kv_service_proto_rawDescGZIP(), []int{0}
}

func (x *PingRequest) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *PingRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

type PingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version uint64 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Body    []byte `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_service_kv_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_service_kv_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_internal_service_kv_service_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *PingResponse) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

// --------------------------------------------------------------------
type Meta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tenant   string  `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	User     *string `protobuf:"bytes,2,opt,name=user,proto3,oneof" json:"user,omitempty"`
	Password *string `protobuf:"bytes,3,opt,name=password,proto3,oneof" json:"password,omitempty"`
}

func (x *Meta) Reset() {
	*x = Meta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_service_kv_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Meta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Meta) ProtoMessage() {}

func (x *Meta) ProtoReflect() protoreflect.Message {
	mi := &file_internal_service_kv_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Meta.ProtoReflect.Descriptor instead.
func (*Meta) Descriptor() ([]byte, []int) {
	return file_internal_service_kv_service_proto_rawDescGZIP(), []int{2}
}

func (x *Meta) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *Meta) GetUser() string {
	if x != nil && x.User != nil {
		return *x.User
	}
	return ""
}

func (x *Meta) GetPassword() string {
	if x != nil && x.Password != nil {
		return *x.Password
	}
	return ""
}

type WritePointsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version uint64 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Meta    *Meta  `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	Points  []byte `protobuf:"bytes,3,opt,name=points,proto3" json:"points,omitempty"` // flatbuffers bytes ( models::Points )
}

func (x *WritePointsRequest) Reset() {
	*x = WritePointsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_service_kv_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WritePointsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WritePointsRequest) ProtoMessage() {}

func (x *WritePointsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_service_kv_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WritePointsRequest.ProtoReflect.Descriptor instead.
func (*WritePointsRequest) Descriptor() ([]byte, []int) {
	return file_internal_service_kv_service_proto_rawDescGZIP(), []int{3}
}

func (x *WritePointsRequest) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *WritePointsRequest) GetMeta() *Meta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *WritePointsRequest) GetPoints() []byte {
	if x != nil {
		return x.Points
	}
	return nil
}

type WritePointsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PointsNumber uint64 `protobuf:"varint,1,opt,name=points_number,json=pointsNumber,proto3" json:"points_number,omitempty"`
}

func (x *WritePointsResponse) Reset() {
	*x = WritePointsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_service_kv_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WritePointsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WritePointsResponse) ProtoMessage() {}

func (x *WritePointsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_service_kv_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WritePointsResponse.ProtoReflect.Descriptor instead.
func (*WritePointsResponse) Descriptor() ([]byte, []int) {
	return file_internal_service_kv_service_proto_rawDescGZIP(), []int{4}
}

func (x *WritePointsResponse) GetPointsNumber() uint64 {
	if x != nil {
		return x.PointsNumber
	}
	return 0
}

// --------------------------------------------------------------------
type FileInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Md5  string `protobuf:"bytes,1,opt,name=md5,proto3" json:"md5,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Size uint64 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
}

func (x *FileInfo) Reset() {
	*x = FileInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_service_kv_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfo) ProtoMessage() {}

func (x *FileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_service_kv_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfo.ProtoReflect.Descriptor instead.
func (*FileInfo) Descriptor() ([]byte, []int) {
	return file_internal_service_kv_service_proto_rawDescGZIP(), []int{5}
}

func (x *FileInfo) GetMd5() string {
	if x != nil {
		return x.Md5
	}
	return ""
}

func (x *FileInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileInfo) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type GetVnodeFilesMetaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tenant  string `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Db      string `protobuf:"bytes,2,opt,name=db,proto3" json:"db,omitempty"`
	VnodeId uint32 `protobuf:"varint,3,opt,name=vnode_id,json=vnodeId,proto3" json:"vnode_id,omitempty"`
}

func (x *GetVnodeFilesMetaRequest) Reset() {
	*x = GetVnodeFilesMetaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_service_kv_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetVnodeFilesMetaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVnodeFilesMetaRequest) ProtoMessage() {}

func (x *GetVnodeFilesMetaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_service_kv_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVnodeFilesMetaRequest.ProtoReflect.Descriptor instead.
func (*GetVnodeFilesMetaRequest) Descriptor() ([]byte, []int) {
	return file_internal_service_kv_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetVnodeFilesMetaRequest) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *GetVnodeFilesMetaRequest) GetDb() string {
	if x != nil {
		return x.Db
	}
	return ""
}

func (x *GetVnodeFilesMetaRequest) GetVnodeId() uint32 {
	if x != nil {
		return x.VnodeId
	}
	return 0
}

type GetVnodeFilesMetaResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path  string      `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Infos []*FileInfo `protobuf:"bytes,2,rep,name=infos,proto3" json:"infos,omitempty"`
}

func (x *GetVnodeFilesMetaResponse) Reset() {
	*x = GetVnodeFilesMetaResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_service_kv_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetVnodeFilesMetaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVnodeFilesMetaResponse) ProtoMessage() {}

func (x *GetVnodeFilesMetaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_service_kv_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVnodeFilesMetaResponse.ProtoReflect.Descriptor instead.
func (*GetVnodeFilesMetaResponse) Descriptor() ([]byte, []int) {
	return file_internal_service_kv_service_proto_rawDescGZIP(), []int{7}
}

func (x *GetVnodeFilesMetaResponse) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *GetVnodeFilesMetaResponse) GetInfos() []*FileInfo {
	if x != nil {
		return x.Infos
	}
	return nil
}

// --------------------------------------------------------------------
type StatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Data string `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_service_kv_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_service_kv_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_internal_service_kv_service_proto_rawDescGZIP(), []int{8}
}

func (x *StatusResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *StatusResponse) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type WriteVnodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VnodeId   uint32 `protobuf:"varint,1,opt,name=vnode_id,json=vnodeId,proto3" json:"vnode_id,omitempty"`
	Tenant    string `protobuf:"bytes,2,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Precision uint32 `protobuf:"varint,3,opt,name=precision,proto3" json:"precision,omitempty"`
	Data      []byte `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *WriteVnodeRequest) Reset() {
	*x = WriteVnodeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_service_kv_service_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WriteVnodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteVnodeRequest) ProtoMessage() {}

func (x *WriteVnodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_service_kv_service_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteVnodeRequest.ProtoReflect.Descriptor instead.
func (*WriteVnodeRequest) Descriptor() ([]byte, []int) {
	return file_internal_service_kv_service_proto_rawDescGZIP(), []int{9}
}

func (x *WriteVnodeRequest) GetVnodeId() uint32 {
	if x != nil {
		return x.VnodeId
	}
	return 0
}

func (x *WriteVnodeRequest) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *WriteVnodeRequest) GetPrecision() uint32 {
	if x != nil {
		return x.Precision
	}
	return 0
}

func (x *WriteVnodeRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type DropDBRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Db string `protobuf:"bytes,1,opt,name=db,proto3" json:"db,omitempty"`
}

func (x *DropDBRequest) Reset() {
	*x = DropDBRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_service_kv_service_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DropDBRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropDBRequest) ProtoMessage() {}

func (x *DropDBRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_service_kv_service_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropDBRequest.ProtoReflect.Descriptor instead.
func (*DropDBRequest) Descriptor() ([]byte, []int) {
	return file_internal_service_kv_service_proto_rawDescGZIP(), []int{10}
}

func (x *DropDBRequest) GetDb() string {
	if x != nil {
		return x.Db
	}
	return ""
}

type DropTableRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Db    string `protobuf:"bytes,1,opt,name=db,proto3" json:"db,omitempty"`
	Table string `protobuf:"bytes,2,opt,name=table,proto3" json:"table,omitempty"`
}

func (x *DropTableRequest) Reset() {
	*x = DropTableRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_service_kv_service_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DropTableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropTableRequest) ProtoMessage() {}

func (x *DropTableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_service_kv_service_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropTableRequest.ProtoReflect.Descriptor instead.
func (*DropTableRequest) Descriptor() ([]byte, []int) {
	return file_internal_service_kv_service_proto_rawDescGZIP(), []int{11}
}

func (x *DropTableRequest) GetDb() string {
	if x != nil {
		return x.Db
	}
	return ""
}

func (x *DropTableRequest) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

type DeleteVnodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Db      string `protobuf:"bytes,1,opt,name=db,proto3" json:"db,omitempty"`
	VnodeId uint32 `protobuf:"varint,2,opt,name=vnode_id,json=vnodeId,proto3" json:"vnode_id,omitempty"`
}

func (x *DeleteVnodeRequest) Reset() {
	*x = DeleteVnodeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_service_kv_service_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteVnodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVnodeRequest) ProtoMessage() {}

func (x *DeleteVnodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_service_kv_service_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVnodeRequest.ProtoReflect.Descriptor instead.
func (*DeleteVnodeRequest) Descriptor() ([]byte, []int) {
	return file_internal_service_kv_service_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteVnodeRequest) GetDb() string {
	if x != nil {
		return x.Db
	}
	return ""
}

func (x *DeleteVnodeRequest) GetVnodeId() uint32 {
	if x != nil {
		return x.VnodeId
	}
	return 0
}

type CopyVnodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VnodeId uint32 `protobuf:"varint,1,opt,name=vnode_id,json=vnodeId,proto3" json:"vnode_id,omitempty"`
}

func (x *CopyVnodeRequest) Reset() {
	*x = CopyVnodeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_service_kv_service_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CopyVnodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyVnodeRequest) ProtoMessage() {}

func (x *CopyVnodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_service_kv_service_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyVnodeRequest.ProtoReflect.Descriptor instead.
func (*CopyVnodeRequest) Descriptor() ([]byte, []int) {
	return file_internal_service_kv_service_proto_rawDescGZIP(), []int{13}
}

func (x *CopyVnodeRequest) GetVnodeId() uint32 {
	if x != nil {
		return x.VnodeId
	}
	return 0
}

type MoveVnodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VnodeId uint32 `protobuf:"varint,1,opt,name=vnode_id,json=vnodeId,proto3" json:"vnode_id,omitempty"`
}

func (x *MoveVnodeRequest) Reset() {
	*x = MoveVnodeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_service_kv_service_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoveVnodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveVnodeRequest) ProtoMessage() {}

func (x *MoveVnodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_service_kv_service_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveVnodeRequest.ProtoReflect.Descriptor instead.
func (*MoveVnodeRequest) Descriptor() ([]byte, []int) {
	return file_internal_service_kv_service_proto_rawDescGZIP(), []int{14}
}

func (x *MoveVnodeRequest) GetVnodeId() uint32 {
	if x != nil {
		return x.VnodeId
	}
	return 0
}

type CompactVnodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VnodeIds []uint32 `protobuf:"varint,1,rep,packed,name=vnode_ids,json=vnodeIds,proto3" json:"vnode_ids,omitempty"`
}

func (x *CompactVnodeRequest) Reset() {
	*x = CompactVnodeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_service_kv_service_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompactVnodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompactVnodeRequest) ProtoMessage() {}

func (x *CompactVnodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_service_kv_service_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompactVnodeRequest.ProtoReflect.Descriptor instead.
func (*CompactVnodeRequest) Descriptor() ([]byte, []int) {
	return file_internal_service_kv_service_proto_rawDescGZIP(), []int{15}
}

func (x *CompactVnodeRequest) GetVnodeIds() []uint32 {
	if x != nil {
		return x.VnodeIds
	}
	return nil
}

type DropColumnRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Db     string `protobuf:"bytes,1,opt,name=db,proto3" json:"db,omitempty"`
	Table  string `protobuf:"bytes,2,opt,name=table,proto3" json:"table,omitempty"`
	Column string `protobuf:"bytes,3,opt,name=column,proto3" json:"column,omitempty"`
}

func (x *DropColumnRequest) Reset() {
	*x = DropColumnRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_service_kv_service_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DropColumnRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropColumnRequest) ProtoMessage() {}

func (x *DropColumnRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_service_kv_service_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropColumnRequest.ProtoReflect.Descriptor instead.
func (*DropColumnRequest) Descriptor() ([]byte, []int) {
	return file_internal_service_kv_service_proto_rawDescGZIP(), []int{16}
}

func (x *DropColumnRequest) GetDb() string {
	if x != nil {
		return x.Db
	}
	return ""
}

func (x *DropColumnRequest) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *DropColumnRequest) GetColumn() string {
	if x != nil {
		return x.Column
	}
	return ""
}

type AddColumnRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Db     string `protobuf:"bytes,1,opt,name=db,proto3" json:"db,omitempty"`
	Table  string `protobuf:"bytes,2,opt,name=table,proto3" json:"table,omitempty"`
	Column []byte `protobuf:"bytes,3,opt,name=column,proto3" json:"column,omitempty"`
}

func (x *AddColumnRequest) Reset() {
	*x = AddColumnRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_service_kv_service_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddColumnRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddColumnRequest) ProtoMessage() {}

func (x *AddColumnRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_service_kv_service_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddColumnRequest.ProtoReflect.Descriptor instead.
func (*AddColumnRequest) Descriptor() ([]byte, []int) {
	return file_internal_service_kv_service_proto_rawDescGZIP(), []int{17}
}

func (x *AddColumnRequest) GetDb() string {
	if x != nil {
		return x.Db
	}
	return ""
}

func (x *AddColumnRequest) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *AddColumnRequest) GetColumn() []byte {
	if x != nil {
		return x.Column
	}
	return nil
}

type AlterColumnRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Db     string `protobuf:"bytes,1,opt,name=db,proto3" json:"db,omitempty"`
	Table  string `protobuf:"bytes,2,opt,name=table,proto3" json:"table,omitempty"`
	Name   string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Column []byte `protobuf:"bytes,4,opt,name=column,proto3" json:"column,omitempty"`
}

func (x *AlterColumnRequest) Reset() {
	*x = AlterColumnRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_service_kv_service_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AlterColumnRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlterColumnRequest) ProtoMessage() {}

func (x *AlterColumnRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_service_kv_service_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlterColumnRequest.ProtoReflect.Descriptor instead.
func (*AlterColumnRequest) Descriptor() ([]byte, []int) {
	return file_internal_service_kv_service_proto_rawDescGZIP(), []int{18}
}

func (x *AlterColumnRequest) GetDb() string {
	if x != nil {
		return x.Db
	}
	return ""
}

func (x *AlterColumnRequest) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *AlterColumnRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AlterColumnRequest) GetColumn() []byte {
	if x != nil {
		return x.Column
	}
	return nil
}

type AdminCommandRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tenant string `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	// Types that are assignable to Command:
	//	*AdminCommandRequest_DropDb
	//	*AdminCommandRequest_DropTab
	//	*AdminCommandRequest_DelVnode
	//	*AdminCommandRequest_CopyVnode
	//	*AdminCommandRequest_MoveVnode
	//	*AdminCommandRequest_CompactVnode
	//	*AdminCommandRequest_DropColumn
	//	*AdminCommandRequest_AddColumn
	//	*AdminCommandRequest_AlterColumn
	Command isAdminCommandRequest_Command `protobuf_oneof:"command"`
}

func (x *AdminCommandRequest) Reset() {
	*x = AdminCommandRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_service_kv_service_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdminCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminCommandRequest) ProtoMessage() {}

func (x *AdminCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_service_kv_service_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminCommandRequest.ProtoReflect.Descriptor instead.
func (*AdminCommandRequest) Descriptor() ([]byte, []int) {
	return file_internal_service_kv_service_proto_rawDescGZIP(), []int{19}
}

func (x *AdminCommandRequest) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (m *AdminCommandRequest) GetCommand() isAdminCommandRequest_Command {
	if m != nil {
		return m.Command
	}
	return nil
}

func (x *AdminCommandRequest) GetDropDb() *DropDBRequest {
	if x, ok := x.GetCommand().(*AdminCommandRequest_DropDb); ok {
		return x.DropDb
	}
	return nil
}

func (x *AdminCommandRequest) GetDropTab() *DropTableRequest {
	if x, ok := x.GetCommand().(*AdminCommandRequest_DropTab); ok {
		return x.DropTab
	}
	return nil
}

func (x *AdminCommandRequest) GetDelVnode() *DeleteVnodeRequest {
	if x, ok := x.GetCommand().(*AdminCommandRequest_DelVnode); ok {
		return x.DelVnode
	}
	return nil
}

func (x *AdminCommandRequest) GetCopyVnode() *CopyVnodeRequest {
	if x, ok := x.GetCommand().(*AdminCommandRequest_CopyVnode); ok {
		return x.CopyVnode
	}
	return nil
}

func (x *AdminCommandRequest) GetMoveVnode() *MoveVnodeRequest {
	if x, ok := x.GetCommand().(*AdminCommandRequest_MoveVnode); ok {
		return x.MoveVnode
	}
	return nil
}

func (x *AdminCommandRequest) GetCompactVnode() *CompactVnodeRequest {
	if x, ok := x.GetCommand().(*AdminCommandRequest_CompactVnode); ok {
		return x.CompactVnode
	}
	return nil
}

func (x *AdminCommandRequest) GetDropColumn() *DropColumnRequest {
	if x, ok := x.GetCommand().(*AdminCommandRequest_DropColumn); ok {
		return x.DropColumn
	}
	return nil
}

func (x *AdminCommandRequest) GetAddColumn() *AddColumnRequest {
	if x, ok := x.GetCommand().(*AdminCommandRequest_AddColumn); ok {
		return x.AddColumn
	}
	return nil
}

func (x *AdminCommandRequest) GetAlterColumn() *AlterColumnRequest {
	if x, ok := x.GetCommand().(*AdminCommandRequest_AlterColumn); ok {
		return x.AlterColumn
	}
	return nil
}

type isAdminCommandRequest_Command interface {
	isAdminCommandRequest_Command()
}

type AdminCommandRequest_DropDb struct {
	DropDb *DropDBRequest `protobuf:"bytes,2,opt,name=drop_db,json=dropDb,proto3,oneof"`
}

type AdminCommandRequest_DropTab struct {
	DropTab *DropTableRequest `protobuf:"bytes,3,opt,name=drop_tab,json=dropTab,proto3,oneof"`
}

type AdminCommandRequest_DelVnode struct {
	DelVnode *DeleteVnodeRequest `protobuf:"bytes,4,opt,name=del_vnode,json=delVnode,proto3,oneof"`
}

type AdminCommandRequest_CopyVnode struct {
	CopyVnode *CopyVnodeRequest `protobuf:"bytes,5,opt,name=copy_vnode,json=copyVnode,proto3,oneof"`
}

type AdminCommandRequest_MoveVnode struct {
	MoveVnode *MoveVnodeRequest `protobuf:"bytes,6,opt,name=move_vnode,json=moveVnode,proto3,oneof"`
}

type AdminCommandRequest_CompactVnode struct {
	CompactVnode *CompactVnodeRequest `protobuf:"bytes,7,opt,name=compact_vnode,json=compactVnode,proto3,oneof"`
}

type AdminCommandRequest_DropColumn struct {
	DropColumn *DropColumnRequest `protobuf:"bytes,8,opt,name=drop_column,json=dropColumn,proto3,oneof"`
}

type AdminCommandRequest_AddColumn struct {
	AddColumn *AddColumnRequest `protobuf:"bytes,9,opt,name=add_column,json=addColumn,proto3,oneof"`
}

type AdminCommandRequest_AlterColumn struct {
	AlterColumn *AlterColumnRequest `protobuf:"bytes,10,opt,name=alter_column,json=alterColumn,proto3,oneof"`
}

func (*AdminCommandRequest_DropDb) isAdminCommandRequest_Command() {}

func (*AdminCommandRequest_DropTab) isAdminCommandRequest_Command() {}

func (*AdminCommandRequest_DelVnode) isAdminCommandRequest_Command() {}

func (*AdminCommandRequest_CopyVnode) isAdminCommandRequest_Command() {}

func (*AdminCommandRequest_MoveVnode) isAdminCommandRequest_Command() {}

func (*AdminCommandRequest_CompactVnode) isAdminCommandRequest_Command() {}

func (*AdminCommandRequest_DropColumn) isAdminCommandRequest_Command() {}

func (*AdminCommandRequest_AddColumn) isAdminCommandRequest_Command() {}

func (*AdminCommandRequest_AlterColumn) isAdminCommandRequest_Command() {}

type BatchBytesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *BatchBytesResponse) Reset() {
	*x = BatchBytesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_service_kv_service_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatchBytesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchBytesResponse) ProtoMessage() {}

func (x *BatchBytesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_service_kv_service_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchBytesResponse.ProtoReflect.Descriptor instead.
func (*BatchBytesResponse) Descriptor() ([]byte, []int) {
	return file_internal_service_kv_service_proto_rawDescGZIP(), []int{20}
}

func (x *BatchBytesResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *BatchBytesResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type DownloadFileRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tenant   string `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Db       string `protobuf:"bytes,2,opt,name=db,proto3" json:"db,omitempty"`
	VnodeId  uint32 `protobuf:"varint,3,opt,name=vnode_id,json=vnodeId,proto3" json:"vnode_id,omitempty"`
	Filename string `protobuf:"bytes,4,opt,name=filename,proto3" json:"filename,omitempty"`
}

func (x *DownloadFileRequest) Reset() {
	*x = DownloadFileRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_service_kv_service_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DownloadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadFileRequest) ProtoMessage() {}

func (x *DownloadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_service_kv_service_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadFileRequest.ProtoReflect.Descriptor instead.
func (*DownloadFileRequest) Descriptor() ([]byte, []int) {
	return file_internal_service_kv_service_proto_rawDescGZIP(), []int{21}
}

func (x *DownloadFileRequest) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *DownloadFileRequest) GetDb() string {
	if x != nil {
		return x.Db
	}
	return ""
}

func (x *DownloadFileRequest) GetVnodeId() uint32 {
	if x != nil {
		return x.VnodeId
	}
	return 0
}

func (x *DownloadFileRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

type FetchVnodeSummaryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tenant   string `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Database string `protobuf:"bytes,2,opt,name=database,proto3" json:"database,omitempty"`
	VnodeId  uint32 `protobuf:"varint,3,opt,name=vnode_id,json=vnodeId,proto3" json:"vnode_id,omitempty"`
}

func (x *FetchVnodeSummaryRequest) Reset() {
	*x = FetchVnodeSummaryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_service_kv_service_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchVnodeSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchVnodeSummaryRequest) ProtoMessage() {}

func (x *FetchVnodeSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_service_kv_service_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchVnodeSummaryRequest.ProtoReflect.Descriptor instead.
func (*FetchVnodeSummaryRequest) Descriptor() ([]byte, []int) {
	return file_internal_service_kv_service_proto_rawDescGZIP(), []int{22}
}

func (x *FetchVnodeSummaryRequest) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *FetchVnodeSummaryRequest) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *FetchVnodeSummaryRequest) GetVnodeId() uint32 {
	if x != nil {
		return x.VnodeId
	}
	return 0
}

type QueryRecordBatchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Args []byte `protobuf:"bytes,1,opt,name=args,proto3" json:"args,omitempty"`
	Expr []byte `protobuf:"bytes,2,opt,name=expr,proto3" json:"expr,omitempty"`
	Aggs []byte `protobuf:"bytes,3,opt,name=aggs,proto3" json:"aggs,omitempty"`
}

func (x *QueryRecordBatchRequest) Reset() {
	*x = QueryRecordBatchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_service_kv_service_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryRecordBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRecordBatchRequest) ProtoMessage() {}

func (x *QueryRecordBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_service_kv_service_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRecordBatchRequest.ProtoReflect.Descriptor instead.
func (*QueryRecordBatchRequest) Descriptor() ([]byte, []int) {
	return file_internal_service_kv_service_proto_rawDescGZIP(), []int{23}
}

func (x *QueryRecordBatchRequest) GetArgs() []byte {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *QueryRecordBatchRequest) GetExpr() []byte {
	if x != nil {
		return x.Expr
	}
	return nil
}

func (x *QueryRecordBatchRequest) GetAggs() []byte {
	if x != nil {
		return x.Aggs
	}
	return nil
}

var File_internal_service_kv_service_proto protoreflect.FileDescriptor

var file_internal_service_kv_service_proto_rawDesc = []byte{
	0x0a, 0x21, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2f, 0x6b, 0x76, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x6b, 0x76, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x22,
	0x3b, 0x0a, 0x0b, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18,
	0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x22, 0x3c, 0x0a, 0x0c,
	0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x22, 0x6e, 0x0a, 0x04, 0x4d, 0x65,
	0x74, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x12, 0x17, 0x0a, 0x04, 0x75, 0x73,
	0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72,
	0x88, 0x01, 0x01, 0x12, 0x1f, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x88, 0x01, 0x01, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x42, 0x0b, 0x0a,
	0x09, 0x5f, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x6c, 0x0a, 0x12, 0x57, 0x72,
	0x69, 0x74, 0x65, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x24, 0x0a, 0x04, 0x6d, 0x65,
	0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6b, 0x76, 0x5f, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x04, 0x6d, 0x65, 0x74, 0x61,
	0x12, 0x16, 0x0a, 0x06, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x06, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x22, 0x3a, 0x0a, 0x13, 0x57, 0x72, 0x69, 0x74,
	0x65, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x23, 0x0a, 0x0d, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0c, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x4e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x22, 0x44, 0x0a, 0x08, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x10, 0x0a, 0x03, 0x6d, 0x64, 0x35, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d,
	0x64, 0x35, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x22, 0x5d, 0x0a, 0x18, 0x47, 0x65,
	0x74, 0x56, 0x6e, 0x6f, 0x64, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x4d, 0x65, 0x74, 0x61, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x64, 0x62, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x64, 0x62, 0x12, 0x19,
	0x0a, 0x08, 0x76, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x07, 0x76, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x22, 0x5b, 0x0a, 0x19, 0x47, 0x65, 0x74,
	0x56, 0x6e, 0x6f, 0x64, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x2a, 0x0a, 0x05, 0x69, 0x6e,
	0x66, 0x6f, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6b, 0x76, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x05, 0x69, 0x6e, 0x66, 0x6f, 0x73, 0x22, 0x38, 0x0a, 0x0e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x22, 0x78, 0x0a, 0x11, 0x57, 0x72, 0x69, 0x74, 0x65, 0x56, 0x6e, 0x6f, 0x64, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x76, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x76, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x64,
	0x12, 0x16, 0x0a, 0x06, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x72, 0x65, 0x63,
	0x69, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x70, 0x72, 0x65,
	0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x1f, 0x0a, 0x0d, 0x44, 0x72,
	0x6f, 0x70, 0x44, 0x42, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x64,
	0x62, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x64, 0x62, 0x22, 0x38, 0x0a, 0x10, 0x44,
	0x72, 0x6f, 0x70, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x64, 0x62, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x64, 0x62, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x74, 0x61, 0x62, 0x6c, 0x65, 0x22, 0x3f, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x56,
	0x6e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x64,
	0x62, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x64, 0x62, 0x12, 0x19, 0x0a, 0x08, 0x76,
	0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x76,
	0x6e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x22, 0x2d, 0x0a, 0x10, 0x43, 0x6f, 0x70, 0x79, 0x56, 0x6e,
	0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x76, 0x6e,
	0x6f, 0x64, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x76, 0x6e,
	0x6f, 0x64, 0x65, 0x49, 0x64, 0x22, 0x2d, 0x0a, 0x10, 0x4d, 0x6f, 0x76, 0x65, 0x56, 0x6e, 0x6f,
	0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x76, 0x6e, 0x6f,
	0x64, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x76, 0x6e, 0x6f,
	0x64, 0x65, 0x49, 0x64, 0x22, 0x32, 0x0a, 0x13, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x63, 0x74, 0x56,
	0x6e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x76,
	0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x08,
	0x76, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x73, 0x22, 0x51, 0x0a, 0x11, 0x44, 0x72, 0x6f, 0x70,
	0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x64, 0x62, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x64, 0x62, 0x12, 0x14, 0x0a,
	0x05, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x61,
	0x62, 0x6c, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x22, 0x50, 0x0a, 0x10, 0x41,
	0x64, 0x64, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x64, 0x62, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x64, 0x62, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x74, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x22, 0x66, 0x0a,
	0x12, 0x41, 0x6c, 0x74, 0x65, 0x72, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x64, 0x62, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x64, 0x62, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x63,
	0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x22, 0xf4, 0x04, 0x0a, 0x13, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x43,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74,
	0x65, 0x6e, 0x61, 0x6e, 0x74, 0x12, 0x34, 0x0a, 0x07, 0x64, 0x72, 0x6f, 0x70, 0x5f, 0x64, 0x62,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6b, 0x76, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x44, 0x72, 0x6f, 0x70, 0x44, 0x42, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x48, 0x00, 0x52, 0x06, 0x64, 0x72, 0x6f, 0x70, 0x44, 0x62, 0x12, 0x39, 0x0a, 0x08, 0x64,
	0x72, 0x6f, 0x70, 0x5f, 0x74, 0x61, 0x62, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e,
	0x6b, 0x76, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x44, 0x72, 0x6f, 0x70, 0x54,
	0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x07, 0x64,
	0x72, 0x6f, 0x70, 0x54, 0x61, 0x62, 0x12, 0x3d, 0x0a, 0x09, 0x64, 0x65, 0x6c, 0x5f, 0x76, 0x6e,
	0x6f, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x6b, 0x76, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x56, 0x6e, 0x6f,
	0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x08, 0x64, 0x65, 0x6c,
	0x56, 0x6e, 0x6f, 0x64, 0x65, 0x12, 0x3d, 0x0a, 0x0a, 0x63, 0x6f, 0x70, 0x79, 0x5f, 0x76, 0x6e,
	0x6f, 0x64, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x6b, 0x76, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x43, 0x6f, 0x70, 0x79, 0x56, 0x6e, 0x6f, 0x64, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x09, 0x63, 0x6f, 0x70, 0x79, 0x56,
	0x6e, 0x6f, 0x64, 0x65, 0x12, 0x3d, 0x0a, 0x0a, 0x6d, 0x6f, 0x76, 0x65, 0x5f, 0x76, 0x6e, 0x6f,
	0x64, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x6b, 0x76, 0x5f, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x4d, 0x6f, 0x76, 0x65, 0x56, 0x6e, 0x6f, 0x64, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x09, 0x6d, 0x6f, 0x76, 0x65, 0x56, 0x6e,
	0x6f, 0x64, 0x65, 0x12, 0x46, 0x0a, 0x0d, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x63, 0x74, 0x5f, 0x76,
	0x6e, 0x6f, 0x64, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x6b, 0x76, 0x5f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x63, 0x74, 0x56,
	0x6e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x0c, 0x63,
	0x6f, 0x6d, 0x70, 0x61, 0x63, 0x74, 0x56, 0x6e, 0x6f, 0x64, 0x65, 0x12, 0x40, 0x0a, 0x0b, 0x64,
	0x72, 0x6f, 0x70, 0x5f, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1d, 0x2e, 0x6b, 0x76, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x44, 0x72,
	0x6f, 0x70, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48,
	0x00, 0x52, 0x0a, 0x64, 0x72, 0x6f, 0x70, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x12, 0x3d, 0x0a,
	0x0a, 0x61, 0x64, 0x64, 0x5f, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1c, 0x2e, 0x6b, 0x76, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x41,
	0x64, 0x64, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48,
	0x00, 0x52, 0x09, 0x61, 0x64, 0x64, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x12, 0x43, 0x0a, 0x0c,
	0x61, 0x6c, 0x74, 0x65, 0x72, 0x5f, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x18, 0x0a, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x6b, 0x76, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x41, 0x6c, 0x74, 0x65, 0x72, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x48, 0x00, 0x52, 0x0b, 0x61, 0x6c, 0x74, 0x65, 0x72, 0x43, 0x6f, 0x6c, 0x75, 0x6d,
	0x6e, 0x42, 0x09, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x22, 0x3c, 0x0a, 0x12,
	0x42, 0x61, 0x74, 0x63, 0x68, 0x42, 0x79, 0x74, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x74, 0x0a, 0x13, 0x44, 0x6f,
	0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x64, 0x62, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x64, 0x62, 0x12, 0x19, 0x0a, 0x08, 0x76, 0x6e, 0x6f,
	0x64, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x76, 0x6e, 0x6f,
	0x64, 0x65, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65,
	0x22, 0x69, 0x0a, 0x18, 0x46, 0x65, 0x74, 0x63, 0x68, 0x56, 0x6e, 0x6f, 0x64, 0x65, 0x53, 0x75,
	0x6d, 0x6d, 0x61, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x65,
	0x6e, 0x61, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65,
	0x12, 0x19, 0x0a, 0x08, 0x76, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x07, 0x76, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x22, 0x55, 0x0a, 0x17, 0x51,
	0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x72, 0x67, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x61, 0x72, 0x67, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x65, 0x78,
	0x70, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x65, 0x78, 0x70, 0x72, 0x12, 0x12,
	0x0a, 0x04, 0x61, 0x67, 0x67, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x61, 0x67,
	0x67, 0x73, 0x32, 0x8b, 0x06, 0x0a, 0x0b, 0x54, 0x53, 0x4b, 0x56, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x3b, 0x0a, 0x04, 0x50, 0x69, 0x6e, 0x67, 0x12, 0x17, 0x2e, 0x6b, 0x76, 0x5f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x6b, 0x76, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x54, 0x0a, 0x0b, 0x57, 0x72, 0x69, 0x74, 0x65, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x12, 0x1e,
	0x2e, 0x6b, 0x76, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x57, 0x72, 0x69, 0x74,
	0x65, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f,
	0x2e, 0x6b, 0x76, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x57, 0x72, 0x69, 0x74,
	0x65, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x28, 0x01, 0x30, 0x01, 0x12, 0x4f, 0x0a, 0x10, 0x57, 0x72, 0x69, 0x74, 0x65, 0x56, 0x6e,
	0x6f, 0x64, 0x65, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x12, 0x1d, 0x2e, 0x6b, 0x76, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x57, 0x72, 0x69, 0x74, 0x65, 0x56, 0x6e, 0x6f, 0x64,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x6b, 0x76, 0x5f, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x5b, 0x0a, 0x10, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x42, 0x61, 0x74, 0x63, 0x68, 0x12, 0x23, 0x2e, 0x6b, 0x76, 0x5f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1e, 0x2e, 0x6b, 0x76, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x42, 0x61, 0x74,
	0x63, 0x68, 0x42, 0x79, 0x74, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x30, 0x01, 0x12, 0x51, 0x0a, 0x10, 0x45, 0x78, 0x65, 0x63, 0x41, 0x64, 0x6d, 0x69, 0x6e,
	0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x1f, 0x2e, 0x6b, 0x76, 0x5f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e,
	0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x6b, 0x76, 0x5f, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x53, 0x0a, 0x0c, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f,
	0x61, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x1f, 0x2e, 0x6b, 0x76, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x46, 0x69, 0x6c, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x6b, 0x76, 0x5f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x42, 0x79, 0x74, 0x65, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x12, 0x62, 0x0a, 0x11, 0x47,
	0x65, 0x74, 0x56, 0x6e, 0x6f, 0x64, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x4d, 0x65, 0x74, 0x61,
	0x12, 0x24, 0x2e, 0x6b, 0x76, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65,
	0x74, 0x56, 0x6e, 0x6f, 0x64, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x4d, 0x65, 0x74, 0x61, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x6b, 0x76, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x56, 0x6e, 0x6f, 0x64, 0x65, 0x46, 0x69, 0x6c, 0x65,
	0x73, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x5b, 0x0a, 0x11, 0x46, 0x65, 0x74, 0x63, 0x68, 0x56, 0x6e, 0x6f, 0x64, 0x65, 0x53, 0x75, 0x6d,
	0x6d, 0x61, 0x72, 0x79, 0x12, 0x24, 0x2e, 0x6b, 0x76, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x46, 0x65, 0x74, 0x63, 0x68, 0x56, 0x6e, 0x6f, 0x64, 0x65, 0x53, 0x75, 0x6d, 0x6d,
	0x61, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x6b, 0x76, 0x5f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x42, 0x79, 0x74,
	0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x52, 0x0a, 0x07,
	0x54, 0x61, 0x67, 0x53, 0x63, 0x61, 0x6e, 0x12, 0x23, 0x2e, 0x6b, 0x76, 0x5f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x6b,
	0x76, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x42,
	0x79, 0x74, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01,
	0x42, 0x0b, 0x5a, 0x09, 0x2e, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_service_kv_service_proto_rawDescOnce sync.Once
	file_internal_service_kv_service_proto_rawDescData = file_internal_service_kv_service_proto_rawDesc
)

func file_internal_service_kv_service_proto_rawDescGZIP() []byte {
	file_internal_service_kv_service_proto_rawDescOnce.Do(func() {
		file_internal_service_kv_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_service_kv_service_proto_rawDescData)
	})
	return file_internal_service_kv_service_proto_rawDescData
}

var file_internal_service_kv_service_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_internal_service_kv_service_proto_goTypes = []interface{}{
	(*PingRequest)(nil),               // 0: kv_service.PingRequest
	(*PingResponse)(nil),              // 1: kv_service.PingResponse
	(*Meta)(nil),                      // 2: kv_service.Meta
	(*WritePointsRequest)(nil),        // 3: kv_service.WritePointsRequest
	(*WritePointsResponse)(nil),       // 4: kv_service.WritePointsResponse
	(*FileInfo)(nil),                  // 5: kv_service.FileInfo
	(*GetVnodeFilesMetaRequest)(nil),  // 6: kv_service.GetVnodeFilesMetaRequest
	(*GetVnodeFilesMetaResponse)(nil), // 7: kv_service.GetVnodeFilesMetaResponse
	(*StatusResponse)(nil),            // 8: kv_service.StatusResponse
	(*WriteVnodeRequest)(nil),         // 9: kv_service.WriteVnodeRequest
	(*DropDBRequest)(nil),             // 10: kv_service.DropDBRequest
	(*DropTableRequest)(nil),          // 11: kv_service.DropTableRequest
	(*DeleteVnodeRequest)(nil),        // 12: kv_service.DeleteVnodeRequest
	(*CopyVnodeRequest)(nil),          // 13: kv_service.CopyVnodeRequest
	(*MoveVnodeRequest)(nil),          // 14: kv_service.MoveVnodeRequest
	(*CompactVnodeRequest)(nil),       // 15: kv_service.CompactVnodeRequest
	(*DropColumnRequest)(nil),         // 16: kv_service.DropColumnRequest
	(*AddColumnRequest)(nil),          // 17: kv_service.AddColumnRequest
	(*AlterColumnRequest)(nil),        // 18: kv_service.AlterColumnRequest
	(*AdminCommandRequest)(nil),       // 19: kv_service.AdminCommandRequest
	(*BatchBytesResponse)(nil),        // 20: kv_service.BatchBytesResponse
	(*DownloadFileRequest)(nil),       // 21: kv_service.DownloadFileRequest
	(*FetchVnodeSummaryRequest)(nil),  // 22: kv_service.FetchVnodeSummaryRequest
	(*QueryRecordBatchRequest)(nil),   // 23: kv_service.QueryRecordBatchRequest
}
var file_internal_service_kv_service_proto_depIdxs = []int32{
	2,  // 0: kv_service.WritePointsRequest.meta:type_name -> kv_service.Meta
	5,  // 1: kv_service.GetVnodeFilesMetaResponse.infos:type_name -> kv_service.FileInfo
	10, // 2: kv_service.AdminCommandRequest.drop_db:type_name -> kv_service.DropDBRequest
	11, // 3: kv_service.AdminCommandRequest.drop_tab:type_name -> kv_service.DropTableRequest
	12, // 4: kv_service.AdminCommandRequest.del_vnode:type_name -> kv_service.DeleteVnodeRequest
	13, // 5: kv_service.AdminCommandRequest.copy_vnode:type_name -> kv_service.CopyVnodeRequest
	14, // 6: kv_service.AdminCommandRequest.move_vnode:type_name -> kv_service.MoveVnodeRequest
	15, // 7: kv_service.AdminCommandRequest.compact_vnode:type_name -> kv_service.CompactVnodeRequest
	16, // 8: kv_service.AdminCommandRequest.drop_column:type_name -> kv_service.DropColumnRequest
	17, // 9: kv_service.AdminCommandRequest.add_column:type_name -> kv_service.AddColumnRequest
	18, // 10: kv_service.AdminCommandRequest.alter_column:type_name -> kv_service.AlterColumnRequest
	0,  // 11: kv_service.TSKVService.Ping:input_type -> kv_service.PingRequest
	3,  // 12: kv_service.TSKVService.WritePoints:input_type -> kv_service.WritePointsRequest
	9,  // 13: kv_service.TSKVService.WriteVnodePoints:input_type -> kv_service.WriteVnodeRequest
	23, // 14: kv_service.TSKVService.QueryRecordBatch:input_type -> kv_service.QueryRecordBatchRequest
	19, // 15: kv_service.TSKVService.ExecAdminCommand:input_type -> kv_service.AdminCommandRequest
	21, // 16: kv_service.TSKVService.DownloadFile:input_type -> kv_service.DownloadFileRequest
	6,  // 17: kv_service.TSKVService.GetVnodeFilesMeta:input_type -> kv_service.GetVnodeFilesMetaRequest
	22, // 18: kv_service.TSKVService.FetchVnodeSummary:input_type -> kv_service.FetchVnodeSummaryRequest
	23, // 19: kv_service.TSKVService.TagScan:input_type -> kv_service.QueryRecordBatchRequest
	1,  // 20: kv_service.TSKVService.Ping:output_type -> kv_service.PingResponse
	4,  // 21: kv_service.TSKVService.WritePoints:output_type -> kv_service.WritePointsResponse
	8,  // 22: kv_service.TSKVService.WriteVnodePoints:output_type -> kv_service.StatusResponse
	20, // 23: kv_service.TSKVService.QueryRecordBatch:output_type -> kv_service.BatchBytesResponse
	8,  // 24: kv_service.TSKVService.ExecAdminCommand:output_type -> kv_service.StatusResponse
	20, // 25: kv_service.TSKVService.DownloadFile:output_type -> kv_service.BatchBytesResponse
	7,  // 26: kv_service.TSKVService.GetVnodeFilesMeta:output_type -> kv_service.GetVnodeFilesMetaResponse
	20, // 27: kv_service.TSKVService.FetchVnodeSummary:output_type -> kv_service.BatchBytesResponse
	20, // 28: kv_service.TSKVService.TagScan:output_type -> kv_service.BatchBytesResponse
	20, // [20:29] is the sub-list for method output_type
	11, // [11:20] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_internal_service_kv_service_proto_init() }
func file_internal_service_kv_service_proto_init() {
	if File_internal_service_kv_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_service_kv_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_service_kv_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_service_kv_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Meta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_service_kv_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WritePointsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_service_kv_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WritePointsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_service_kv_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_service_kv_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetVnodeFilesMetaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_service_kv_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetVnodeFilesMetaResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_service_kv_service_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_service_kv_service_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WriteVnodeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_service_kv_service_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DropDBRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_service_kv_service_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DropTableRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_service_kv_service_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteVnodeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_service_kv_service_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CopyVnodeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_service_kv_service_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MoveVnodeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_service_kv_service_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CompactVnodeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_service_kv_service_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DropColumnRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_service_kv_service_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddColumnRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_service_kv_service_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AlterColumnRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_service_kv_service_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdminCommandRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_service_kv_service_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BatchBytesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_service_kv_service_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DownloadFileRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_service_kv_service_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchVnodeSummaryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_service_kv_service_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryRecordBatchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_internal_service_kv_service_proto_msgTypes[2].OneofWrappers = []interface{}{}
	file_internal_service_kv_service_proto_msgTypes[19].OneofWrappers = []interface{}{
		(*AdminCommandRequest_DropDb)(nil),
		(*AdminCommandRequest_DropTab)(nil),
		(*AdminCommandRequest_DelVnode)(nil),
		(*AdminCommandRequest_CopyVnode)(nil),
		(*AdminCommandRequest_MoveVnode)(nil),
		(*AdminCommandRequest_CompactVnode)(nil),
		(*AdminCommandRequest_DropColumn)(nil),
		(*AdminCommandRequest_AddColumn)(nil),
		(*AdminCommandRequest_AlterColumn)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_service_kv_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_service_kv_service_proto_goTypes,
		DependencyIndexes: file_internal_service_kv_service_proto_depIdxs,
		MessageInfos:      file_internal_service_kv_service_proto_msgTypes,
	}.Build()
	File_internal_service_kv_service_proto = out.File
	file_internal_service_kv_service_proto_rawDesc = nil
	file_internal_service_kv_service_proto_goTypes = nil
	file_internal_service_kv_service_proto_depIdxs = nil
}
